{% set version = "1.1.35" %}

package:
  name: libxslt
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/libxslt/{{ version[0:3] }}/libxslt-{{ version }}.tar.xz
  sha256: 8247f33e9a872c6ac859aa45018bc4c4d00b97e2feac9eebc10c93ce1f34dd79
  patches:
    - 0001-Make-and-install-a-pkg-config-file-on-Windows.patch
    - 0002-win-profiler-config.patch

build:
  number: 1
  run_exports:
    # forward compatible: https://abi-laboratory.pro/tracker/timeline/libxslt/
    - {{ pin_subpackage('libxslt') }}
  # ignore_run_exports:
  #   - icu  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - gnuconfig  # [unix]
    - make
    - pkg-config
  host:
    - icu  # [not win]
    - libiconv
    - libxml2
    - libzlib
    - xz

test:
  requires:
    - pkg-config
  commands:
    - xsltproc --version
    - pkg-config --cflags libxslt libexslt
    - pkg-config --libs libxslt libexslt

about:
  home: https://gitlab.gnome.org/GNOME/libxslt
  license: MIT
  license_file: COPYING
  summary: The XSLT C library developed for the GNOME project
  description: |
    "Libxslt is the XSLT C library developed for the GNOME project.
    XSLT itself is a an XML language to define transformation for XML.
    Libxslt is based on libxml2 the XML C library developed for the GNOME project.
    It also implements most of the EXSLT set of processor-portable extensions functions
    and some of Saxon's evaluate and expressions extensions."
  doc_url: https://gitlab.gnome.org/GNOME/libxslt/-/wikis
  dev_url: https://gitlab.gnome.org/GNOME/libxslt
  doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
